#!/bin/bash

print() {
  cat << EOF > ./config/www/index.html.tmp
  <!DOCTYPE html>
  <html>
  <meta http-equiv="refresh" content="30">
  <head>
  <style>
	body {
			font-family: Helvetica, Arial, sans-serif;
			font-size: 13px;

			word-wrap: break-word;

			max-width: 90%;
			min-height: 100%;
			margin:2% auto;
	}
  hr {
  animation: slidein 1s;
  color: #1ABC9C;

  }
  :root {
    --mainColor: #1ABC9C;
  }
  a {
     background:
     linear-gradient(
       to bottom, var(--mainColor) 0%,
       var(--mainColor) 100%
     );
    background-position: 0 100%;
    background-repeat: repeat-x;
    background-size: 0px 0px;
    color: #1ABC9C;	
    text-size: 15px;
    text-decoration: none;
    transition: background-size .3s;
    font-weight: bold;
    padding-top: 5px;
    padding-bottom: 5px;
    padding-right: 10px;
    padding-left: 10px;
  }
  a:hover {
	color: #000;
        background-size: 8px 90px;
  }
  header {
     text-align: left;
		 letter-spacing: 3px;
  }

  .rice {
  	font-weight: 100; 
	border-style: solid;
	border-width: 1px;
	border-color: #404044;
	padding-right: 20px;
	padding-left: 20px;
	  margin-top: 4px;
  }

  @keyframes slidein {
  from {
  margin-left: 100%;
  width: 300%; 
  }
  
  to {
  margin-left: 0%;
  width: 100%;
  }
}
  </style>
  </head>
  <body>
	<header>
	<h1 style="text-align:center;text-decoration: underline; font-weight: 150;">iofq.net</h1>
	<a href="https://iofq.net">status</a> | <a href="https://git.iofq.net">github</a> | <a href="mailto: cjriddz@protonmail.com">email</a> | <a href="https://gpg.iofq.net">PGP</a> | <a href="https://s.iofq.net">url shortener</a> | <a href="https://top.iofq.net">top</a> | <a href="https://swap.iofq.net">uniswap</a>
	</header>
  <div class="rice">

EOF
echo -e "\033[0;36m$(date)\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  screenfetch -d '-gpu;' | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  echo -e "\033[0;35m------ CPU --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  iostat --human | tail -n +3 | head -n -7 | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  top -o %CPU -b -n 1 | awk '{ printf("%-8s  %-8s  %-8s %-8s\n", $2, $9, $10, $12); }' | tail -n +7 | head -n 6 | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  echo -e "\033[0;32m------ Disks --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  iostat --human -m | tail -n +6 | head -n -3 | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  lsblk --output NAME,SIZE,MOUNTPOINT | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  df -h --output=target,size,used,avail,pcent -x tmpfs -x devtmpfs -x overlay | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  echo -e "\033[0;33m------ Network --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
	  cat ./.speedtest.tmp | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
	ifstat -i br0 -b 1 1 | tail -n 1 | awk '{$1/=1024;$2/=1024;printf "\n%.2fMbps in,\t %.2fMbps out\n",$1,$2}' | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  echo -e "\033[0;34m------ Docker --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.CPUPerc}}\t{{.NetIO}}\t{{.BlockIO}}" | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  echo -e "\033[0;35m------ Torrents --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  cat /srv/docker/transmission/status.txt | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  echo -e "\033[0;36m------ Monero node log --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  docker logs --tail 25 monerod &> tmp.log
  tail -n 25 tmp.log | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  #echo -e "\033[0;31m------ Ethereum node log --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  #docker logs --tail 25 eth &> tmp.log
  #tail -n 25 tmp.log | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  # echo -e "\033[0;31m------ ETH 2.0 Beacon node log --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  # journalctl -n 10 --unit lighthouse_beacon | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp
  # echo -e "\033[0;32m------ ETH 2.0 Validator log --------------------------------\033[0m" | ./bin/ansi2html.sh --palette=tango --bg=dark  >> ./config/www/index.html.tmp
  # journalctl -n 10 --unit lighthouse_validator | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/index.html.tmp

  cat << EOF >> ./config/www/index.html.tmp
  </div>
  </body>
  </html>
  <head>
	<footer>
	<p style="font-size: 16px;font-weight: 150; color: #404044"> [powered by nginx and ansi2html] </p>
	</footer>
  </html>
EOF
}

while true; do
  print
  cp ./config/www/index.html.tmp ./config/www/index.html
  sleep 10
done
