#!/bin/bash
print() {
  cat << EOF > ./config/www/top.html.tmp
  <!DOCTYPE html>
  <html>
  <meta http-equiv="refresh" content="10">
  <head>
  <style>
	body {
			font-family: Helvetica, Arial, sans-serif;
			font-size: 13px;

			word-wrap: break-word;

			max-width: 90%;
			min-height: 100%;
			margin:2% auto;
	}
  hr {
  animation: slidein 1s;
  color: #1ABC9C;

  }
  :root {
    --mainColor: #1ABC9C;
  }
  a {
     background:
     linear-gradient(
       to bottom, var(--mainColor) 0%,
       var(--mainColor) 100%
     );
    background-position: 0 100%;
    background-repeat: repeat-x;
    background-size: 0px 0px;
    color: #1ABC9C;	
    text-size: 15px;
    text-decoration: none;
    transition: background-size .3s;
    font-weight: bold;
    padding-top: 5px;
    padding-bottom: 5px;
    padding-right: 10px;
    padding-left: 10px;
  }
  a:hover {
	color: #000;
        background-size: 8px 90px;
  }
  header {
     text-align: left;
		 letter-spacing: 3px;
  }

  .rice {
  	font-weight: 100; 
  background: #000000;
	border-style: solid;
	border-width: 1px;
	border-color: #404044;
	padding-right: 20px;
	padding-left: 20px;
	  margin-top: 4px;
  }

  @keyframes slidein {
  from {
  margin-left: 100%;
  width: 300%; 
  }
  
  to {
  margin-left: 0%;
  width: 100%;
  }
}
  </style>
  </head>
  <body>
	<header>
	<h1 style="text-align:center;text-decoration: underline; font-weight: 150;">iofq.net</h1>
	<a href="https://iofq.net">status</a> | <a href="https://git.iofq.net">github</a> | <a href="mailto: cjriddz@protonmail.com">email</a> | <a href="https://gpg.iofq.net">PGP</a> | <a href="https://s.iofq.net">url shortener</a> | <a href="https://top.iofq.net">top</a> | <a href="https://swap.iofq.net">uniswap</a>
	</header>
  <div class="rice">

EOF
  top -b -n 1 -U '!root' | head -n 50 | ./bin/ansi2html.sh --palette=tango --bg=dark >> ./config/www/top.html.tmp
  cat << EOF >> ./config/www/top.html.tmp
  </div>
  </body>
  </html>
  <head>
	<footer>
	<p style="font-size: 16px;font-weight: 150; color: #404044"> [powered by nginx and ansi2html] </p>
	</footer>
  </html>
EOF
}

while true; do
  print
  cp ./config/www/top.html.tmp ./config/www/top.html
  sleep 1
done
