name: pinata_cloud

on:
  push:
    branches:
      - master
      - workflow

jobs:
  push_ipfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependancies
        run: npm install axios fs form-data recursive-fs base-path-converter

      - name: add source directory to IPFS
        run: |
          echo 'IPFS_HASH=$(docker run -q --rm -v $(pwd):/src ipfs/go-ipfs add -Qr /src | tail -n 1)' >> $GITHUB_ENV

      - name: format 
        run: echo $IPFS_HASH && curl http://cloudflare-ipfs.com/ipfs/${{ env.IPFS_HASH }}

      # - name: Push src to Pinata and hash to Cloudflare APIs
      #   env:
      #     PINATA_CLOUD_TOKEN: ${{ secrets.PINATA_CLOUD_TOKEN }}
      #     CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
      #     CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      #     CLOUDFLARE_RECORD: ${{ secrets.CLOUDFLARE_RECORD }}
      #   run: |
      #     node pinata.js
