name: pinata_cloud

on:
  push:
    branches:
      - master
      - workflow

jobs:
  push_ipfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependancies
        run: npm install axios fs form-data recursive-fs base-path-converter

      - name: run IPFS
        run: |
          echo 'IPFS_HASH<<EOF' >> $GITHUB_ENV
          docker run --rm -d -v $(pwd):/src ipfs/go-ipfs add -Qrn /src | tail -n 1
          echo 'EOF' >> $GITHUB_ENV

      - name: f
        run: echo $IPFS_HASH

      # - name: Push src to Pinata and hash to Cloudflare APIs
      #   env:
      #     PINATA_CLOUD_TOKEN: ${{ secrets.PINATA_CLOUD_TOKEN }}
      #     CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
      #     CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      #     CLOUDFLARE_RECORD: ${{ secrets.CLOUDFLARE_RECORD }}
      #   run: |
      #     node pinata.js
